## Numpy library
* NumPy is a Open Source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

- NumPy is the fundamental package for scientific computing with Python , having following important functionalities: 
     - A powerful N-dimensional array object
     - A sophisticated (broadcasting) functions
     - Contains tools for integrating C/C++ and Fortran code
     - Have  useful  linear algebra, Fourier transform, and random number capabilities

### Why NUMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,



## Installation
- **Anaconda**: A free distribution of Python with scientific packages. Supports Linux, Windows and Mac 
     
        To install numpy type : conda install -c anaconda numpy


- **pip**:Most major projects upload official packages to the Python Package index. They can be installed on most operating systems using Python’s standard pip package manager.

You can install packages via one of the following Commands:

     python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
     
     pip install numpy

## Importing Nympy & Checking Version


In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
# import numpy & pandas
import numpy as np


In [3]:
np.__version__

'1.21.5'

## Bounding numpy package to local variable

The numpy package is bound to the local variable numpy. The **import as** syntax simply allows you to **bind the import to the local variable** name of your choice (usually to avoid name collisions, shorten verbose module names, or standardize access to modules with compatible APIs).

In [4]:
a =(1,2,3,4,5)

In [5]:
type(a)

tuple

In [6]:
b=np.array(a)
print (b)

[1 2 3 4 5]


## Speed Comaprison numpy vs core python

In [7]:
import time

In [8]:
import time as tm
time_python =tm.time()
print(time_python)

1671194303.0148556


In [9]:
import time 
import numpy as np
size_1=1000000
def pure_python_version():
    time_python =time.time()
    list1=range(size_1)
    list2=range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    return time.time() - time_python

def numpy_version():
    time_numpy = time.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    return time.time() - time_numpy
python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",format(python_time))
print("numpy =",format(numpy_time))


pure python version= 0.889998197555542
numpy = 0.02199721336364746


# Creating Arrays

The basic ndarray is created using an array function in NumPy which creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [10]:
my_list=[2,3,4,6,7,8,'Numpy']

In [11]:
my_list

[2, 3, 4, 6, 7, 8, 'Numpy']

In [12]:
my_array=np.array(my_list)
my_array

array(['2', '3', '4', '6', '7', '8', 'Numpy'], dtype='<U11')

In [13]:
my_array.dtype

dtype('<U11')

In [14]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
array_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
type(array_2)

list

In [17]:
array_3= np.array(array_2)
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.ndim(array_3)

2

In [19]:
array_3.dtype

dtype('int32')

In [20]:
type(array_3)

numpy.ndarray

In [21]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [22]:
a = np.array([1, 2, 3,7,5,1], ndmin = 1) 
print (a)
np.ndim(a)

[1 2 3 7 5 1]


1

In [23]:
a = np.array([1, 2, 3,7,5,1], ndmin = 3) 
print (a)
np.ndim(a)

[[[1 2 3 7 5 1]]]


3

In [24]:
type(a)

numpy.ndarray

In [25]:
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [26]:
a = np.array([1, 2, 3]) 
print (a)

[1 2 3]


In [27]:
type(a)

numpy.ndarray

In [28]:
a.dtype

dtype('int32')

In [29]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
len(array_3)

3

In [31]:
array_3[2]

array([7, 8, 9])

In [32]:
array_3[1][-1]

6

In [33]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [34]:
array_3[0]

array([1, 2, 3])

In [35]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [36]:
array_3[2,:] # Acessing Column

array([7, 8, 9])

In [37]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
type(array_3)

numpy.ndarray

In [39]:
array_3[1:3,2:3]

array([[6],
       [9]])

In [40]:
array_3[0,1] # (row

2

## Array Atrributes
Numpy Arrays are conveinent and fast as compared to Python Lists. 1.Shape(no of rows & columns)

In [41]:
array_3.shape #Rows*Column


(3, 3)

In [42]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
array_3.ndim

2

- **ndim** for checking dimension of array

In [44]:
array_3.dtype

dtype('int32')

- **dtype** for checking data type of array 

### Array Initilization


In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [47]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [49]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [51]:
np.linspace(3,4,10)

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

In [52]:
np.linspace(3,4,10).reshape(5,2)

array([[3.        , 3.11111111],
       [3.22222222, 3.33333333],
       [3.44444444, 3.55555556],
       [3.66666667, 3.77777778],
       [3.88888889, 4.        ]])

In [53]:
np.eye(4,4) #Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Initilization with Random numbers
In various applications( like assigning weights in Artificial Neural Networks) arrays need to be initialised randomly. 
for this purpose there are various predefined functions in Numpy(reshape and random)


In [54]:
np.random.rand(3)

array([0.45295108, 0.95976273, 0.57593743])

In [55]:
np.random.randint(100)

38

In [56]:
np.random.randint(1,100000000000)

ValueError: high is out of bounds for int32

In [63]:
np.random.rand(2,3)

array([[0.00661937, 0.83788099, 0.65607491],
       [0.72359451, 0.74090724, 0.94889218]])

In [64]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
np.random.rand(9).reshape(3,3)

array([[0.06509505, 0.30611156, 0.17511689],
       [0.70969827, 0.06733279, 0.64984903],
       [0.09435516, 0.85724143, 0.87831862]])

# Indexing arrays

In [66]:
array_1 = np.arange(1,15)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
array_1[2]

3

In [68]:
array_1[2:6]

array([3, 4, 5, 6])

In [69]:
array_1[-3]

12

In [70]:
array_1[:-3] # before values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
array_1[-3:] #after values

array([12, 13, 14])

In [72]:
array_1[2:6]=8 #mutable i.e to change the member value of array

In [73]:
array_1

array([ 1,  2,  8,  8,  8,  8,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
array_2=[[1,2,3],[4,5,6],[7,8,9]]
array_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [75]:
np.array(array_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
#import numpy as np
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [77]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.arange(2,40,16)

array([ 2, 18, 34])

In [79]:
a=np.eye(3,3)

In [80]:
a[1:3]

array([[0., 1., 0.],
       [0., 0., 1.]])

In [81]:
a[1:0]

array([], shape=(0, 3), dtype=float64)

In [82]:
a[1:2]


array([[0., 1., 0.]])

In [83]:
a=[[1,2,3],[4,5,6],[8,8,9]]
z=np.array(a)
a

[[1, 2, 3], [4, 5, 6], [8, 8, 9]]

In [84]:
z.min()

1

In [85]:
z.max()

9

In [86]:
z.mean()

5.111111111111111

In [87]:
z.argmin()

0

In [88]:
z.argmax()

8

In [89]:
a=[[1,2,3],[4,5,6],[8,8,9]]
z=np.array(a)

In [90]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [91]:
z.reshape(9,1) # 1D to 2D 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [8],
       [8],
       [9]])

In [92]:
z.flatten() #2D to 1D

array([1, 2, 3, 4, 5, 6, 8, 8, 9])

In [93]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [94]:
z.transpose()

array([[1, 4, 8],
       [2, 5, 8],
       [3, 6, 9]])

In [95]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [96]:
z.reshape(1,9) # 1d to 2D

array([[1, 2, 3, 4, 5, 6, 8, 8, 9]])

### Maths 


In [97]:
import numpy as np
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print("Adding to arrays: ")
print(A + B)
print("\nSubstracting Two Arrays:")
print(A-B)
print("\nMultiplying two arrays: ")
print(A * B)
print("\nMultiplying one Array with scalar:")
print(3*A)
print("\nMatrix Multiplication:")
print(np.dot (A,B))

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]

Substracting Two Arrays:
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]

Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]

Multiplying one Array with scalar:
[[12 30 33]
 [63 66 69]
 [93 96 99]]

Matrix Multiplication:
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [98]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [99]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [100]:
a = np.array([0,30,45,60,90]) 

print ('Sine of different angles:' )
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180) )
print ("\n") 

print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180) )
print ("\n") 

print ('Tangent values for given angles:' )
print (np.tan(a*np.pi/180) )

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [101]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print(a)
print (np.around(a)) 
print (np.around(a, decimals = 1))
print (np.around(a, decimals = 2))

[[11.667 23.662]
 [33.21  45.887]]
[[12. 24.]
 [33. 46.]]
[[11.7 23.7]
 [33.2 45.9]]
[[11.67 23.66]
 [33.21 45.89]]


### Stats

In [102]:
A.sum()

187

In [103]:
A.mean()

20.77777777777778

In [104]:
np.std(A)

9.88576729757121

In [105]:
np.median(A)

22.0

In [106]:
np.mod(A,B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.var(A)#Variance

97.72839506172839

## Binary UnivarsalFunction

In [108]:
A=[[1,2,3],[3,4,5]]
B=[[3,3,4],[1,2,0]]
a=np.array(A)
b=np.array(B)
np.greater_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [109]:
np.less(a,b)

array([[ True,  True,  True],
       [False, False, False]])

In [110]:
np.less(b,a)

array([[False, False, False],
       [ True,  True,  True]])

## Subsetting Array

In [111]:
subset=a[:,0]=1 #subset elment before postion 0 to value 1

In [112]:
subset

1

In [113]:
print(a)

[[1 2 3]
 [1 4 5]]


## Concatenating array

In [114]:
A=[[1,2,3],[3,4,5]]
B=[3,3,4],[1,2,0]
a=np.array(A)
b=np.array(B)

In [115]:
a,b

(array([[1, 2, 3],
        [3, 4, 5]]),
 array([[3, 3, 4],
        [1, 2, 0]]))

In [116]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 3, 3, 4],
       [3, 4, 5, 1, 2, 0]])

In [117]:
np.concatenate([a,b],axis=0) # Row wise VVI for EDA purposed

array([[1, 2, 3],
       [3, 4, 5],
       [3, 3, 4],
       [1, 2, 0]])

## Broadcasting
Broadcasting is a method to overcome size of the smaller array by duplicacy so that it is the dimensionality and size as the larger array.

### Why Broadcasting?
To solve the problem of arithmetic with arrays with different sizes.

In [118]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [119]:
np.ndim(b)

1

In [120]:
#### Array with different shapes
![image.png](attachment:image.png)

'[image.png]' is not recognized as an internal or external command,
operable program or batch file.


In [121]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([0.0,1.0,2.0])  
   
print ('First array:\n',a )
print ('Second array:\n',b )
print ("\n")   
print ('First Array + Second Array=\n',a+b)

First array:
 [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
 [0. 1. 2.]


First Array + Second Array=
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


## File Input Output


In [122]:
#The np.save stores the input array in a disk file with npy extension.

a = np.array([11,2,30,4,5,13]) 
np.save('dar',a)

In [123]:
# To reconstruct array from demofile.npy, use load() function.
b = np.load('dar.npy') 
print (b)

[11  2 30  4  5 13]


In [124]:
np.savetxt('dar.txt',a) 
b = np.loadtxt('dar.txt') 
print (b)

[11.  2. 30.  4.  5. 13.]
