In [1]:
import numpy as np

In [2]:
arr1= np.array([11,21,31,41,49])

In [3]:
arr1

array([11, 21, 31, 41, 49])

In [4]:
arr2=np.array([[1,9,11],[21,31,41],[33,67,49]])

In [5]:
arr2

array([[ 1,  9, 11],
       [21, 31, 41],
       [33, 67, 49]])

In [6]:
arr3 = np.array([[15,2,33,4,4,-8],[23,12,33,20,9,43]])

In [7]:
arr3

array([[15,  2, 33,  4,  4, -8],
       [23, 12, 33, 20,  9, 43]])

In [8]:
arr1.sum()

153

In [9]:
arr2.sum()

263

In [10]:
arr3.sum()

190

In [11]:
arr2.sum(axis=0) # row wise addition

array([ 55, 107, 101])

In [12]:
arr2.sum(axis=1)# column wise addition

array([ 21,  93, 149])

In [13]:
arr3.sum(axis=1)

array([ 50, 140])

In [14]:
arr3.sum(axis=0)

array([38, 14, 66, 24, 13, 35])

In [15]:
np.average(arr1)

30.6

In [16]:
np.average(arr2)

29.22222222222222

In [17]:
np.average(arr3)

15.833333333333334

In [18]:
np.average(arr1,axis=0)

30.6

In [19]:
np.average(arr1,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [21]:
np.average(arr2,axis=0)

array([18.33333333, 35.66666667, 33.66666667])

In [22]:
np.average(arr2,axis=1)

array([ 7.        , 31.        , 49.66666667])

In [23]:
np.average(arr3,axis=0)

array([19. ,  7. , 33. , 12. ,  6.5, 17.5])

In [24]:
np.average(arr3,axis=1)

array([ 8.33333333, 23.33333333])

In [25]:
arr1.ndim # checing dimmention

1

In [26]:
arr2.ndim

2

In [27]:
arr3.ndim

2

In [28]:
arr1.min()

11

In [29]:
arr1.max()

49

In [30]:
arr2.min()

1

In [31]:
arr2.max()

67

In [32]:
arr3.min()

-8

In [33]:
arr3.max()

43

In [34]:
arr3.min(axis=0)

array([15,  2, 33,  4,  4, -8])

In [35]:
arr3.max(axis=0)

array([23, 12, 33, 20,  9, 43])

In [36]:
arr3.min(axis=1)

array([-8,  9])

In [37]:
arr3.max(axis=1)

array([33, 43])

In [38]:
arr1.mean()

30.6

In [39]:
arr2.mean()

29.22222222222222

In [40]:
arr3.mean()

15.833333333333334

In [41]:
arr2.mean(1)#col wise

array([ 7.        , 31.        , 49.66666667])

In [42]:
arr2.mean(0)# row wise

array([18.33333333, 35.66666667, 33.66666667])

In [43]:
arr3.mean(0)

array([19. ,  7. , 33. , 12. ,  6.5, 17.5])

In [44]:
arr3.mean(1)

array([ 8.33333333, 23.33333333])

### Computation on array :Broadcasting

* The term broadcasting refers to how numpy treats arrays with different Dimension
while arithmetic operations leading to specific constraints. Moreover, the smaller array is broadcast across the larger array so that they have compatible shapes.

* Broadcasting provides a means of vectorising array operations so that looping occurs in C rather than Python as we understand that Numpy implemented in C programming
language.

* It does this without creating unnecessary data copies and which leads to efficient
algorithm implementations.

* In some cases, broadcasting is a bad idea because it leads to ineffective memory
utilisation which declines the computation.

In [45]:
a1 = np.array([1,3,7,5])
b1 = np.array([90,50,0,30])

In [46]:
c1=a1+b1

In [47]:
c1

array([91, 53,  7, 35])

In [48]:
d1=3

In [49]:
e1=a1*d1
e1

array([ 3,  9, 21, 15])

In [50]:
f1=a1+d1
f1

array([ 4,  6, 10,  8])

### Broadcasting Rules:
• The following are the rules in order to broadcast two arrays together:
1. Prepend the shape of the lower rank array with 1s until both shapes have the same
length if the arrays do not have the same rank
2. In a dimension, the two arrays are compatible if they have the same size in the
dimension or if one of the arrays has size 1 in that dimension
3. If arrays are compatible with all dimensions then they can be broadcasted together
4. After broadcasting, every array acts as if it had shape equivalent to the element‐wise maximum of shapes of the two input arrays
5. In any dimension where one array had size 1, as well as the other array had size greater than 1, the first array acts as if it were copied along that dimension

In [51]:
# 2 dimention
a2=np.array([[12,23,34],[11,21,31]])

In [52]:
a2

array([[12, 23, 34],
       [11, 21, 31]])

In [53]:
a2.ndim

2

In [54]:
b2=4

In [55]:
c2=a2+b2

In [56]:
c2

array([[16, 27, 38],
       [15, 25, 35]])

In [57]:
d2=np.array([1,5,6,7])
a2=np.array([1,2,3,4])

In [58]:
d2

array([1, 5, 6, 7])

In [59]:
d2.ndim

1

In [60]:
e2=d2*a2

In [61]:
e2

array([ 1, 10, 18, 28])

### random function

A two‐dimensional array is generated by the first array having a size of 5 rows and 
columns, and the values are within 10 and 50

A random three‐dimensional array of size 2*3*6 is generated by this second array. The
generated random values are within 1 and 20

In [62]:
arr_ran = np.random.randint(10,50,size=(5,8))

In [63]:
arr_ran

array([[44, 27, 31, 26, 46, 43, 31, 39],
       [48, 22, 11, 35, 38, 25, 32, 23],
       [11, 27, 20, 45, 35, 24, 26, 20],
       [36, 24, 27, 48, 47, 21, 32, 38],
       [45, 11, 26, 31, 41, 30, 25, 22]])

In [64]:
arr_ran.ndim

2

In [65]:
arr1_ran = np.random.randint(1,20,size=(2,3,6))

In [66]:
arr1_ran

array([[[15,  3,  6, 13, 16, 10],
        [16,  3, 14,  6,  8, 13],
        [ 3, 15,  7, 14,  3,  5]],

       [[15, 14, 13, 18,  7,  4],
        [14, 17,  4, 10, 16, 15],
        [ 9,  9, 19,  3, 13, 17]]])

In [67]:
arr1_ran.ndim

3

In [68]:
a=np.array([0,2,3,0,1,6,5,2])

In [69]:
a

array([0, 2, 3, 0, 1, 6, 5, 2])

In [70]:
np.greater(a,2)

array([False, False,  True, False, False,  True,  True, False])

In [71]:
np.greater_equal(a,2)

array([False,  True,  True, False, False,  True,  True,  True])

In [72]:
np.less(a,2)

array([ True, False, False,  True,  True, False, False, False])

In [73]:
np.less_equal(a,2)

array([ True,  True, False,  True,  True, False, False,  True])

In [74]:
a=np.reshape(np.arange(25),(5,5))

In [75]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
greater_value = (a>10)

In [77]:
greater_value

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [78]:
even_value=(a%2==0)
odd_value=(a%2!=0)

In [79]:
even_value

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [80]:
odd_value

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [81]:
b = ~ (a%10 ==0)

In [82]:
b

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [83]:
c = (a%2==0)|(a%3==0)

In [84]:
c

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False,  True]])

In [85]:
d = (a%2==0)&(a%3==0)

In [86]:
d

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

### Masking in numpy

In numpy.ma.mask_rows() function, mask rows of a 2‐Dimensional array which hold
masked values. The numpy.ma.mask_rows() function is a shortcut to mask_rowcols
with axis equal to 0

In [87]:
import numpy as np
import numpy.ma as MA

In [88]:
array=np.zeros((4,4),dtype=int)

In [89]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
array[2,2]=1

In [91]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [92]:
array = MA.masked_equal(array,1)

In [93]:
array

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, --, 0],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],
  fill_value=1)

In [94]:
mask_row=MA.mask_rows(array)

In [95]:
mask_row

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [--, --, --, --],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]],
  fill_value=1)

In [96]:
mask_row_col=MA.mask_rowcols(array)

In [97]:
mask_row_col

masked_array(
  data=[[0, 0, --, 0],
        [0, 0, --, 0],
        [--, --, --, --],
        [0, 0, --, 0]],
  mask=[[False, False,  True, False],
        [False, False,  True, False],
        [ True,  True,  True,  True],
        [False, False,  True, False]],
  fill_value=1)

In [98]:
arr2

array([[ 1,  9, 11],
       [21, 31, 41],
       [33, 67, 49]])

In [99]:
mask_arr2=MA.masked_equal(arr2,33)

In [100]:
mask_arr2

masked_array(
  data=[[1, 9, 11],
        [21, 31, 41],
        [--, 67, 49]],
  mask=[[False, False, False],
        [False, False, False],
        [ True, False, False]],
  fill_value=33)

In [101]:
arr2_row = MA.mask_rows(mask_arr2)

In [102]:
mask_arr2

masked_array(
  data=[[1, 9, 11],
        [21, 31, 41],
        [--, 67, 49]],
  mask=[[False, False, False],
        [False, False, False],
        [ True, False, False]],
  fill_value=33)

In [103]:
arr2_row_col = MA.mask_rowcols(mask_arr2)

In [104]:
arr2_row_col

masked_array(
  data=[[--, 9, 11],
        [--, 31, 41],
        [--, --, --]],
  mask=[[ True, False, False],
        [ True, False, False],
        [ True,  True,  True]],
  fill_value=33)

## Fancy Indexing
* Fancy indexing is like the simple indexing, but we pass arrays of indices instead of single scalars
* It permits us to quickly access as well as change complicated subsets of an array's values

### Exploring Fancy Indexing

* Fancy indexing is conceptually simple which means passing an array of indices in order to access multiple array elements at one time

* For instance, consider the below‐written array:

In [105]:
x=np.random.randint(100,size=10)

In [106]:
x

array([29, 98, 79, 95, 76, 60, 54, 32, 42, 98])

 • Let us suppose, we want to access three different elements
         [x[3],x[7],x[2]]

In [107]:
[x[3],x[7],x[2]]

[95, 32, 79]

On the other hand, we can pass an array of indices or a single list for getting the same result:

In [108]:
ind = [3,7,2]

In [109]:
x[ind]

array([95, 32, 79])

 While utilising fancy indexing, the shape of the result reflects the shape of the index varrays instead of the shape of the array being indexed:

In [110]:
ind1=np.array([[3,7],[4,5]])

In [111]:
x[ind1]

array([[95, 32],
       [76, 60]])

The first index refers to the row, and the second to the column Like with standard
indexing:

In [112]:
y=np.arange(12).reshape((3,4))

In [113]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
row = np.array([0,1,2])
col = np.array([2,1,3])


In [115]:
row

array([0, 1, 2])

In [116]:
col

array([2, 1, 3])

In [117]:
y[row,col]

array([ 2,  5, 11])

• The broadcasting rules are followed by the pairing of indices in fancy indexing.

Therefore, for instance, we get a two‐dimensional result if we combine a column vector
as well as a row vector within the indices:

In [118]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
y[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

• It is always necessary to memorise with fancy indexing that the broadcasted shape of the indices is reflected by the return value, instead of the shape of the array being indexed

### Combined Indexing

* Fancy indexing can be combined with the other indexing schemes for more powerful
operations:

* We can combine fancy indexing with slicing as well:

* Even, fancy indexing can be combined with masking:

* All of these indexing options combined lead to a very flexible group of operations for accessing as well as modifying array values

In [120]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
y[2,[2,0,2]]

array([10,  8, 10])

In [122]:
y[2,[2,0,3]]

array([10,  8, 11])

In [123]:
y[2:,[2,0,3]]

array([[10,  8, 11]])

In [124]:
y[1:,[2,0,3]]

array([[ 6,  4,  7],
       [10,  8, 11]])

In [125]:
mask = np.array([1,0,1,0],dtype = bool)

In [126]:
mask

array([ True, False,  True, False])

In [127]:
y[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### Modifying Values with Fancy Indexing

* Fancy indexing can be used for accessing parts of an array. Moreover, it can modify parts of an array as well. For instance, assume we have an array of indices, and we want to set similar items in an array to some value:


In [128]:
a= np.arange(10)
i=np.array([2,1,8,4])
a[i]=99

print(a)

[ 0 99 99  3 99  5  6  7 99  9]


In [129]:
a= np.arange(10)
i=np.array([2,1,8,4])

a[i] -=10
print(a)

[ 0 -9 -8  3 -6  5  6  7 -2  9]


In [130]:
a=np.zeros(10)
a[[0,0]] = [2,8]

Notice that, repeated indices with these operations can cause some potentially unexpected outcomes
The outcome of this operation is to first assign A[0] = 8, followed by A[0] = 23. The result is that A[0] contains the value 23



In [131]:
array = np.array([5,7,6,7])
as1=np.sort(array)

In [132]:
print(as1)

[5 6 7 7]


In [133]:
arr_name = np.array(['Pine_apple','Banana',"Fig"])
fruit=np.sort(arr_name)
print(fruit)

['Banana' 'Fig' 'Pine_apple']


In [134]:
arr_bool = np.array([False,True,False])
arr_b = np.sort(arr_bool)
print(arr_b)

[False False  True]


In [135]:
arr_sort_2d = np.array([[5,0,2],[9,3,6]])

In [136]:
arr_r = np.sort(arr_sort_2d)
print(arr_r)

[[0 2 5]
 [3 6 9]]


### Numpy Structured Array

• Numpy’s Structured Array is similar to Struct in C programming language. It is used in order to group data of different sizes and types

• Data containers named as fields are used by the structure array. Every data field can contain data of any size and type. With the help of dot notation, array elements can be accessed

#### Structured Array Properties

• All structs in the array have the similar number of fields

• All structs have same fields names

• For instance, consider a student's structured array with different fields such as year,name, and marks

• Every record in array student has a structure of class Struct. Moreover, the array of a structure is referred to as struct as adding any new fields for a new struct in the array, contains the empty array

In [137]:
import numpy as np 

In [138]:
a1 = np.array([('Anagha',2022,8.88),('Sumit',2021,9.88),('Suman',2020,9.70),('kalyani',2021,7.88)],
             dtype = [("Name",(np.str_,10)),('Year',np.int32),("CGPA",np.float64)])

In [139]:
a1

array([('Anagha', 2022, 8.88), ('Sumit', 2021, 9.88),
       ('Suman', 2020, 9.7 ), ('kalyani', 2021, 7.88)],
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [140]:
print(a1)

[('Anagha', 2022, 8.88) ('Sumit', 2021, 9.88) ('Suman', 2020, 9.7 )
 ('kalyani', 2021, 7.88)]


In [141]:
b = np.sort(a1,order='Name')

In [142]:
b

array([('Anagha', 2022, 8.88), ('Suman', 2020, 9.7 ),
       ('Sumit', 2021, 9.88), ('kalyani', 2021, 7.88)],
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [143]:
c = np.sort(a1,order='Year')
c

array([('Suman', 2020, 9.7 ), ('Sumit', 2021, 9.88),
       ('kalyani', 2021, 7.88), ('Anagha', 2022, 8.88)],
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [144]:
d = np.sort(a1,order='CGPA')
d

array([('kalyani', 2021, 7.88), ('Anagha', 2022, 8.88),
       ('Suman', 2020, 9.7 ), ('Sumit', 2021, 9.88)],
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [145]:
a1[a1['Name']=='Sumit']

array([('Sumit', 2021, 9.88)],
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [146]:
a1['Name'=='']

array([], shape=(0, 4),
      dtype=[('Name', '<U10'), ('Year', '<i4'), ('CGPA', '<f8')])

In [150]:
a1[0][0]

'Anagha'